version: '3.8'

services:
  web:
    image: my-flask-app:multistage
    ports:
      - "5002:5000"
    depends_on:
      - mydb

  mydb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw