version: '3.8'

services:
  # Building web container and setting port
  web:
    build: .
    expose:
    - "5002"
    depends_on:
    - redisdb
    # Setting up environment variables
    environment:
    - REDIS_HOST=redisdb
    - REDIS_PORT=6379
  
  # Creating Redis container with ports and persistent volume
  redisdb:
    image: "redis:latest"
    ports:
    - "6379:6379"
    volumes:
      - redisdb-data:/data

  # Setting up nginx container
  nginx:
    image: nginx:latest
    ports:
      - "5002:5002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

# Creating volume for persistent storage
volumes:
  redisdb-data: 