version: '3.8'

services:
  web:
    build: .
    expose:
    - "5002"
    depends_on:
    - redisdb
    environment:
    - REDIS_HOST=redisdb
    - REDIS_PORT=6379
  
  redisdb:
    image: "redis:latest"
    ports:
    - "6379:6379"
    volumes:
      - redisdb-data:/data

  nginx:
    image: nginx:latest
    ports:
      - "5002:5002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

volumes:
  redisdb-data: 